[#828] fix the travis build task
looks like it does not like the strict mode :
/home/travis/build/melonjs/melonJS/node_modules/grunt-eslint/tasks/eslint.js:2
const chalk = require('chalk');
^^^^^
Loading "eslint.js" tasks...ERROR
>> SyntaxError: Use of const in strict mode.
Warning: Task "eslint:beforeConcat" not found. Use --force to continue.
Aborted due to warnings.
npm ERR! Test failed.  See above for more details.